[NoSpoiler] tagscript support
ltzmax/maxcogs pull request #74
Opened 2023-10-14 19:53 UTC by japandotorg

test this thoroughly before merging

2023-10-14 21:31 UTC, ltzmax commented on nospoiler/nospoiler.py
> +        await ctx.send(f"The delete after is now {amount}.")
Due to the limit from discord and avoiding rate limit, should be from  5 sec and 120 sec.

2023-10-14 21:36 UTC, ltzmax requested changes
Got one error in logs when having delete enabled.
```py
Oct 14 21:34:08 max python[568319]: future: <Task finished name='Task-506103' coro=<PartialMessage.delete.<locals>.delete() done, defined at /home/max/redenv/lib/python3.11/site-packages/discord/message.py:850> exception=TypeError("'<=' not supported between instances of '_ValueCtxManager' and 'int'")>
Oct 14 21:34:08 max python[568319]: Traceback (most recent call last):
Oct 14 21:34:08 max python[568319]:   File "/home/max/redenv/lib/python3.11/site-packages/discord/message.py", line 851, in delete
Oct 14 21:34:08 max python[568319]:     await asyncio.sleep(delay)
Oct 14 21:34:08 max python[568319]:   File "/usr/lib/python3.11/asyncio/tasks.py", line 634, in sleep
Oct 14 21:34:08 max python[568319]:     if delay <= 0:
Oct 14 21:34:08 max python[568319]:        ^^^^^^^^^^
Oct 14 21:34:08 max python[568319]: TypeError: '<=' not supported between instances of '_ValueCtxManager' and 'int'
```
Also have to add in info.json in requirements that tagscript is needed.

2023-10-15 05:13 UTC, japandotorg commented
> Got one error in logs when having delete enabled.

ah forgot to await lol

2023-10-15 09:28 UTC, japandotorg commented
should be fixed now!

2023-10-15 10:45 UTC, ltzmax requested changes
Mostly good, just two more things.

2023-10-15 10:45 UTC, ltzmax commented on nospoiler/nospoiler.py
> +        self, ctx: commands.Context, *, message: TagscriptConverter
This has to be optional else it won't clear back to default.

2023-10-15 10:45 UTC, ltzmax commented on nospoiler/nospoiler.py
> +    @nospoiler.command()
```suggestion
    @nospoiler.command(aliases=["timeout"])
```

2023-10-15 10:53 UTC, ltzmax requested changes

2023-10-15 10:53 UTC, ltzmax commented on nospoiler/nospoiler.py
> +        ```
I think its fair to show title too.
```suggestion
        ```
        {embed(title):No spoiler allowed.}
        {embed(description):{member(mention)} You cannot send spoilers here.}
        {embed(color):{color}}
        ```
```

2023-10-15 12:24 UTC, ltzmax requested changes
Make sure to add `orjson` into requirements too.

2023-10-15 12:24 UTC, ltzmax commented on nospoiler/__init__.py
> +    data = json.load(f)
```suggestion
with open(Path(__file__).parent / "info.json") as f:
    data = orjson.loads(f.read())
```

2023-10-15 12:24 UTC, ltzmax commented on nospoiler/__init__.py
> +from pathlib import Path
```suggestion
import orjson
from pathlib import Path
```

2023-10-15 13:22 UTC, ltzmax approved these changes

2023-10-15 13:22 UTC, merged